name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag rifkinauvaldzaki/portofolio-rifki:latest || true

      - name: Debugging Information
        run: |
          echo "Current working directory:"
          pwd
          echo "Listing files:"
          ls -la

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push the Docker image
        run: docker push rifkinauvaldzaki/portofolio-rifki:latest
