name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your main branch
  pull_request:
    branches:
      - main  # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
        run: |
          docker build --build-arg RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} -t rifkinauvaldzaki/portofolio-rifki:latest .
          
      - name: Push Docker image
        run: |
          docker push rifkinauvaldzaki/portofolio-rifki:latest
